### ISSUE TITLE
V1 using extensions with dict is wrong

### ISSUE THREAD

**Issue by vaikas** [cloudevents/sdk-python#32] opened 2020-04-24 23:22 UTC
Using a very minimalistic event results in a non-worky cloud events:

```sh
vaikas-a01:sdk-python-master vaikas$ python3 ./app2.py
{'content-type': 'application/cloudevents+json'}
b'{"specversion": "1.0", "id": "my-id", "source": "from-vaikas", "type": "vaikas.test", "datacontenttype": "application/json", "data": "{\\"HELLO\\": \\"FROM VILLE\\"}", "extensions": {}}'
```

Workaround:
https://github.com/cloudevents/sdk-python/blob/master/cloudevents/sdk/event/v1.py#L31

Removing this line makes it work (but then you can't use extensions):
in v1.py
#        self.ce__extensions = opt.Option("extensions", dict(), False)

Repro code:
```py
event = (
    v1.Event().
    SetContentType("application/json").
    SetEventID("my-id").
    SetSource("from-vaikas").
    SetEventType("vaikas.test").
    SetData('{"HELLO": "FROM VILLE"}')
)

m = marshaller.NewHTTPMarshaller(
    [
        structured.NewJSONHTTPCloudEventConverter()
    ]
)
```

#broker url

#url = 'http://localhost:8080/'
# get headers and body
```py
headers, body = m.ToRequest(event, converters.TypeStructured, lambda x: x)
print(headers)
print(body.getvalue())
```

#send the request
response = requests.post(url, headers=headers, data=body)

**Comment by di** [comment] 2020-04-28 00:22
If I'm understanding correctly, this might be a duplicate of https://github.com/cloudevents/sdk-python/issues/24 and fixed by https://github.com/cloudevents/sdk-python/pull/25.

Can you try the master branch of this repo and see if you can still reproduce this?

**Comment by vaikas** [comment] 2020-04-28 20:44
@di I don't actually think it fixes the problem. This only fixed the headers, but in my case I was using structured events where the extensions get incorrectly marshalled into the body. I had pulled the head on Friday and looks like #25 was already there. I'll try to verify this in the next couple of days, but I think the big different is between structured mode vs. binary, which looks like the fix / tests handle?

**Comment by grant** [comment] 2020-05-28 17:17
From the conversation in the CE SDK meeting, it seems like this a violation of conformance with the spec.

**Comment by cumason123** [comment] 2020-06-19 19:49
Hey, I'm new to this community but can you elaborate a little more on what your issue with extensions is @vaikas

**Comment by evankanderson** [comment] 2020-07-10 22:42
Extensions should be treated the same as any other top-level attribute; it sounds like they were serialized incorrectly in structured mode. We should probably make sure that we have tests covering this case.

**Closed** 2020-07-24 19:04 UTC
