### ISSUE TITLE
`CloudEvent` object should support `get` operations

### ISSUE THREAD

**Issue by ace-n** [cloudevents/sdk-python#147] opened 2021-11-24 23:51 UTC
## Expected Behavior

The CloudEvent object supports `.get()` operations, a la [Python dictionaries](https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey/).

## Actual Behavior

The CloudEvent object does not support `.get()`, and says it's undefined.

## Workaround

Use the `in` operator to check if the desired property is provided within the CloudEvent object.

## Steps to Reproduce the Problem

Setup code
```
from cloudevents.http import CloudEvent

attributes = {
    "source": "test",
    "type": "google.cloud.audit.log.v1.written",
    "subject": "storage.googleapis.com/projects/_/buckets/my-bucket/objects/test.txt",
}

data = {
    "protoPayload": {
        "methodName": "storage.objects.create",
        "authenticationInfo": {"principalEmail": "nobody@example.com"},
        "resourceName": "some-resource",
    }
}

event = CloudEvent(attributes, data)
```

Test code
```
# Will not work
event.get('subject')

# Only works if `subject` is specified; otherwise a `KeyError` is thrown
event['subject']

# Workaround
if 'subject' in event:
    event['subject']
```

## Specifications

- Platform: Mac OSX
- Python Version: Python 3.7.2
- CloudEvents Python SDK version: 1.2.0

**Comment by grant** [comment] 2021-12-10 00:44
Thanks Ace. I believe this issue is a duplicate of this other issue: https://github.com/cloudevents/sdk-python/issues/49
What do you think?

I think direct accessors for the standard CE attributes makes sense.

**Comment by grant** [comment] 2021-12-10 01:39
Sounds good. We can keep track in that other issue. I just mentioned you and this suggestion.

The comment is also linked in the GitHub UI.

**Closed by grant** 2021-12-10 01:39 UTC
